import { attribute, autoGeneratedHashKey, table } from '@aws/dynamodb-data-mapper-annotations';
import { Table } from 'sst/node/table';

@table(Table.merch.tableName)
export class Merch {
  constructor(model?: Partial<Merch>) {
    if (model) {
      Object.assign(this, model);
    }
  }

  @autoGeneratedHashKey({ attributeName: 'merchId' })
  id!: string;

  @attribute()
  title!: string;

  @attribute()
  createdAt!: number;
}
