import { attribute, autoGeneratedHashKey, table } from '@aws/dynamodb-data-mapper-annotations';
import { Table } from 'sst/node/table';

@table(Table.merch.tableName)
export class Merch {
  constructor(model?: Partial<Merch>) {
    if (model) {
      Object.assign(this, model);
    }
  }

  @autoGeneratedHashKey()
  merchId!: string;

  @attribute()
  status!: number;

  @attribute()
  vendor!: string;

  @attribute()
  title!: string;

  @attribute()
  price!: number;

  @attribute()
  description?: string;

  @attribute()
  createdAt!: number;

  @attribute()
  createdBy!: string;

  @attribute()
  modifiedAt?: number;

  @attribute()
  modifiedBy?: string;
}
