import { attribute, autoGeneratedHashKey, table } from '@aws/dynamodb-data-mapper-annotations';

@table('Merch')
export class Merch {
  @autoGeneratedHashKey({ attributeName: 'merchId' })
  id!: string;

  @attribute()
  title!: string;
}
